global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: local

scrape_configs:

  - job_name: user-api
    metrics_path: /api/v1/actuator/prometheus
    static_configs:
      - targets: [ 'user-api:8080' ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance

  - job_name: projects-api
    metrics_path: /api/v1/actuator/prometheus
    static_configs:
      - targets: [ 'projects-api:8081' ]
